language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo apt-get install -qq libgmp-dev libmpfr-dev
  - sudo apt-get install -qq python-numpy python-scipy
notifications:
  email:
    recipients:
      - dkuragin@ya.ru
      - kuragin@speaktoit.com
script: make test