<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!--
Robot model taken from http://wiki.ros.org/pr2_mechanism/Tutorials/SImple%20URDF-Controller%20Example
-->
  <xacro:include filename="$(find hdf_urdf)/robots/wheel.xacro"/>

  <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>

  <!-- Constants for robot dimensions -->
  <xacro:property name="width" value="0.01" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="wheel_radius" value="0.01" /> <!-- Link 1 -->
  <xacro:property name="thickness" value="0.001" /> <!-- Link 2 -->
  <xacro:property name="axel_offset" value="0.0025" /> <!-- Space btw top of beam and the each joint -->

  <!-- Links: inertial,visual,collision -->
  <link name="base_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${width} 0.045 0.045"/>
      </geometry>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${width} 0.1 0.1"/>
      </geometry>
    </collision>
  </link>


  <!--link name="base_footprint">
    <visual>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.00000001"/>
      </geometry>
    </collision>
  </link>
  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    <child link="base_link"/>
    <parent link="base_footprint"/>
  </joint-->


  <!-- Wheels -->
  <wheel name="front_left_wheel" parent="base" radius="${wheel_radius}" thickness="${thickness}">
    <origin xyz="${width/2+axel_offset} 0 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </wheel>
  <wheel name="front_right_wheel" parent="base" radius="${wheel_radius}" thickness="${thickness}">
    <origin xyz="${-width/2+axel_offset} 0 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </wheel>



<link
    name="laser_link">
    <inertial>
      <origin
        xyz="0.00660628943773761 0.0102231270512427 0.0109910978700269"
        rpy="1.57 0 1.57" />
      <mass
        value="0.142293449327418" />
      <inertia
        ixx="8.01694611303598E-05"
        ixy="-1.99081597083089E-07"
        ixz="7.5632515219276E-08"
        iyy="4.9027575487778E-05"
        iyz="2.63391723380498E-08"
        izz="7.99749503749484E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="1.57 0 1.57" />
      <geometry>
        <mesh
          filename="$(find hdf_urdf)/robots/laser_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="1.57 0 1.57" />
      <geometry>
        <mesh
          filename="$(find hdf_urdf)/robots/laser_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="laser_joint"
    type="fixed">
    <origin
      xyz="0.17393 -0.0065502 0.15326"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="laser_link" />
    <axis
      xyz="0 0 0" />
  </joint>



  <!-- Colour -->
  <gazebo reference="base_link">
    <material>Gazebo/Green</material>
  </gazebo>

  <!--gazebo reference="base_footprint">
    <material>Gazebo/Purple</material>
  </gazebo-->

</robot>
