# Publish all joint states -----------------------------------
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10 
 
diffbot_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'front_left_wheel_joint'
  right_wheel: 'front_right_wheel_joint'
  publish_rate: 10.0 # defaults to 50
  pose_covariance_diagonal: [0.000001, 0.001, 0.0000001, 0.000001, 0.001, 0.03]
  twist_covariance_diagonal: [0.000001, 0.001, 0.001, 0.000001, 0.001, 0.03]
  cmd_vel_timeout: 20
  enable_odom_tf_: true

