# Odometry model:
odom_model_type: diff
odom_alpha1    : 0.4
odom_alpha2    : 0.4
odom_alpha3    : 0.8
odom_alpha4    : 0.2
#odom_alpha5    : 0.1

# Particle filter:
min_particles    : 500
max_particles    : 5000
kld_err          : 0.05
kld_z            : 0.99
update_min_d     : 0.1
update_min_a     : 0.5
resample_interval: 1

# Measurement (laser) model:
laser_model_type         : likelihood_field
laser_max_beams          : 30
laser_z_hit              : 0.5
laser_z_short            : 0.05
laser_z_max              : 0.05
laser_z_rand             : 0.5
laser_sigma_hit          : 0.2
laser_lambda_short       : 0.1
laser_lambda_short       : 0.1
laser_likelihood_max_dist: 2.0

#initial pose
initial_pose_x : -0.073182
initial_pose_y : -0.069906
initial_pose_a : -0.5

# Update/Rate params:
transform_tolerance: 0.2
gui_publish_rate   : 10.0

# Recovery:
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

# Frames:
odom_frame_id: odom
#base_frame_id: base_link
#global_frame_id: map

#receive_map_topic: true
#use_map_topic: map
