local_costmap:
  global_frame: /odom
  robot_base_frame: /base_link
  update_frequency: 2
  publish_frequency: 2
  static_map: true
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.1
  inflation_radius: 0.3
  cost_scaling_factor: 0.5

